import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// The generation history + caption cache live in a local sidecar server
// (server/index.mjs, default port 8787), not in the browser. Same-origin via
// this proxy so the client needs no CORS and no absolute URL.
const API_PORT = process.env.PE_API_PORT || 8787
const apiProxy = {
  '/api': { target: `http://localhost:${API_PORT}`, changeOrigin: false },
}

// strictPort: a silent move to 5174/5175 when 5173 is busy changes the page
// origin. That used to also change which IndexedDB opened (→ "history is empty
// again"); the data is out of the browser now, but a second app instance racing
// one sidecar is still wrong — fail loudly instead.
export default defineConfig({
  plugins: [react()],
  server:  { strictPort: true, proxy: apiProxy },
  preview: { strictPort: true, proxy: apiProxy },
  // `npm test` (vitest). The suites cover the pure modules only — prompt
  // assembly, the LoRA repair, the hash the sidecar shares — so plain node is
  // the right environment; nothing here touches the DOM.
  //
  // test/prompts.test.js holds GOLDEN MASTERS: every system prompt and every
  // assembled user message, snapshotted. They exist so a refactor can be proven
  // not to change a single generated byte. A snapshot diff is therefore a
  // finding to investigate, never something to wave through with `-u`.
  test: {
    environment: 'node',
    include: ['test/**/*.test.{js,jsx}'],
  },
})
